/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddCategoryPopup: typeof import('./src/components/addCategoryPopup/index.vue')['default']
    AddEntryPopup: typeof import('./src/components/addEntryPopup/index.vue')['default']
    ConfigProvider: typeof import('./src/components/configProvider/index.vue')['default']
    CustomHeader: typeof import('./src/components/customHeader/index.vue')['default']
    GradientHeader: typeof import('./src/components/gradientHeader/index.vue')['default']
    NutBarrage: typeof import('@nutui/nutui-taro')['Barrage']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCellGroup: typeof import('@nutui/nutui-taro')['CellGroup']
    NutConfigProvider: typeof import('@nutui/nutui-taro')['ConfigProvider']
    NutEmpty: typeof import('@nutui/nutui-taro')['Empty']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutPicker: typeof import('@nutui/nutui-taro')['Picker']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutSpace: typeof import('@nutui/nutui-taro')['Space']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutUploader: typeof import('@nutui/nutui-taro')['Uploader']
  }
}
